### ISSUE TITLE
POKE-dex

### ISSUE THREAD

**Issue by iiviigames** [gamegeist/Picopedia#6]
# `poke`-dex

Perhaps you're a child of the 90's.  
Perhaps not.

This is a Pokédex:

![pokedex]

A Pokédex tells those who strive to catch'em all what exactly the sentient lava slug in front of it is capable of.

**We PICO-8 developers have need of something quite similar,** as we're living in a world where we've got to deal with a thing that does _a whole lot of stuff_ and has no definitive list of what that stuff is.

> 🆘   
> 🛟 I'm here to help.

## The `POKE` Function

Before I continue on about the things this can do, let's consult the [official manual](https://www.lexaloffle.com/dl/docs/pico-8_manual.html#POKE), or read the code block below.

---

POKE(ADDR, VAL1, VAL2, ...)

> Write one or more bytes to an address in base ram.  
> If more than one parameter is provided, they are written sequentially `(max: 8192)`

---

![scarn]

...okay, fine.

While this _does tell us_ **how & why** `POKE` does something, that diabolic genius [zep](https://twitter.com/lexaloffle) is messing with your mind. 

You see, that part of the documentation doesn't appear until damn near the end, but...(check this for yourself if you doubt me)...

**HE'S BEEN USING IT TO DO ALL TYPES OF STUFF IN EARLIER PARTS OF THE DOCS**! 

I hear you already. 

> _Who cares?_  

Well... 

> 🆔🅾️

Here's a few reasons why. 

1. The docs as they stand are not newcomer friendly. This is especially true of the [memory](https://www.lexaloffle.com/dl/docs/pico-8_manual.html#Memory) section. 
   - I am uncertain if this is intentional due to PICO-8's _"seek and ye shall find"_ attitude and philosophy, but even if it is, I don't think it's good enough of a reason to not undertake what I am about to.
2. The `POKE` function is inherently an intermediate - advanced feature of the API, yet, **it's needed to do some extremely basic and appealing things**. 
   - It's used in **`21` cases** before it is given a definition in the manual. This just isn't the way.
3. Before one `POKE`s the Memory Hornet's Nest, they should understand **why they are doing it**. 
   - The manual will tell you some things `POKE` does, but you're going to be in the dark without further study of the memory layout, external tools, cartridge specific uses, or someone with the ability to cast a [wish spell]() in your party,

I mean, I get its still not "official" but come on, if you want to enable **mouse and keyboard** actions[^1], this is allowed through the following sillyness:

```lua
-- flags below
POKE(0x5F2D, flags) 
--[
0x1 Enable
0x2 Mouse buttons trigger btn(4)..btn(6)
0x4 Pointer lock
 - use stat 38..39 to read movements
]]--
```

## Imagine If P8SCII Was Handled Like This

But it's not. It has it's pretty, well explained _appendix_ all to itself. 

**WHERE IS THE `POKE` APPENDIX**?!?! 

> <del>It doesn't exist</del>  
> Until now... 

# Coming Soon... 

I've been working on a lot of stuff over the years. I have a robust wiki for Pico-8 that was gonna be for the book, (but that's on perma-hold)   and it's got a lot of good data that doesn't exist elsewhere. 

What we'll have at the end is the reference we need. This is something far too big to put on the [unofficial API](https://iiviigames.github.io/pico8-api), and so it will be released here, or on its own site, or maybe a GitHub wiki. I don't know yet. 

## 🛣️ Roadmap 🗺️

- [ ] Provide thorough and detailed explanations for `POKE` and the other memory functions often used in conjunction with it
- [ ] Gather every known usage of the `POKE` function
- [ ] When the functionality is fully mapped, provide inline references to relevant information... 
- [ ] Create visual associations with the parts of memory the particular `POKE` action is altering, reinforcing long term retention of hexadecimal values via colors... 
- [ ] Include definitions for the argument which alters the memory, and why it does... 
- [ ] Provide practical examples for their use, including demos wherever possible... **and**
- [ ] Display this information in a easily readable, searchable, usable way
- [ ] _Maybe_ get a basic API so vscode and st users can basically have a full dictionary of hinting available to them during the coding process. 

---

**Your Brother in Development,**

> ❤️ _[Vee (iiviigames/core nerd)](https://twitch.tv/iiviigames)_

[^1]: The [Mouse Data](https://www.lexaloffle.com/dl/docs/pico-8_manual.html#Mouse_and_Keyboard_Input) <sup>It doesn't use <code>POKE</code> to read it...it uses <code>STAT</code></sup>

[#]: "IMAGES"

[pokedex]: <https://github.com/gamegeist/Picopedia/assets/43127314/af87cffa-13f2-4f22-8eb4-a973f398a9c1> "A Copyright Safe Pokédex" 

[scarn]: <https://github.com/gamegeist/Picopedia/assets/43127314/75fba6b6-dc10-419d-bdf7-4178f188ffa4> "Michael is exasperated at this definition"
